using Xunit;

namespace SkillMatrixManagement.EntityFrameworkCore;

[CollectionDefinition(SkillMatrixManagementTestConsts.CollectionDefinitionName)]
public class SkillMatrixManagementEntityFrameworkCoreCollection : ICollectionFixture<SkillMatrixManagementEntityFrameworkCoreFixture>
{

}
