using SkillMatrixManagement.EntityFrameworkCore;
using Xunit;

namespace SkillMatrixManagement.EntityFrameworkCore;

public class SkillMatrixManagementEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<SkillMatrixManagementEntityFrameworkCoreFixture>
{

}
