using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SkillMatrixManagement.Constants;
using SkillMatrixManagement.Models;
using Volo.Abp.Domain.Repositories;

namespace SkillMatrixManagement.Repositories
{
    public interface IReportAnalyticsRepository : IBasicRepository<ReportAnalytics, Guid>
    {
        // CRUD Methods
        Task<ReportAnalytics> CreateAsync(ReportAnalytics reportAnalytics);
        Task<ReportAnalytics> GetByIdAsync(Guid id);
        Task<List<ReportAnalytics>> GetAllAsync();
        Task UpdateAsync(ReportAnalytics reportAnalytics);
        Task DeleteAsync(Guid reportAnalyticsId); // Soft delete
        Task PermanentDeleteAsync(Guid reportAnalyticsId); // Hard delete

        // Soft Delete & Restore
        Task SoftDeleteAsync(Guid reportAnalyticsId); // Soft delete a report analytics record
        Task RestoreReportAnalyticsAsync(Guid reportAnalyticsId); // Restore a soft-deleted report analytics record

        // Custom Methods
        Task<List<ReportAnalytics>> GetReportsByGeneratedByAsync(Guid userId); // Get all reports generated by a specific user
        Task<List<ReportAnalytics>> GetReportsByTypeAsync(ReportTypeEnum reportType); // Get all reports by report type
    }
}
